version: "2"
services:
  dev_api_envios:
    container_name: dev_api_envios
#    image: dev_api_envios:1.0
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host="0.0.0.0" --port=9766 --reload
    volumes:
      - /usr/local/volumes/fileserver/devenvios/:/app/fileserver/
    ports:
      - "9766:9766"
#services:
  # Our main app
#  envios:
#    build: .
#    command: uvicorn main:app --host 0.0.0.0 --port 9776 --reload
#    volumes:
#      - ./tancho:/tancho
#    ports:
#      - "9776:9776"
#    depends_on:
#        - mongo

  # MongoDB as a service
#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "tancho"
#      MONGO_INITDB_ROOT_PASSWORD: "4dm1n4dm1n"
#    volumes:
#        - mongo_data:/data/db
#    ports:
#      - "27017:27017"
