version: '2'

#volumes:
#    mongo_data:

services:
  # Our main app
  envios:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 9776 --reload
#    volumes:
#      - ./tancho:/tancho
    ports:
      - "9776:9776"
#    depends_on:
#        - mongo

  # MongoDB as a service
#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "tancho"
#      MONGO_INITDB_ROOT_PASSWORD: "4dm1n4dm1n"
#    volumes:
#        - mongo_data:/data/db
#    ports:
#      - "27017:27017"
